name: miba-hackathon
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pytest=8.4.2
  - pytest-cov=7.0.0
  - pandas=2.2.3
  - numpy=2.1.2
  - scikit-learn=1.5.2
  - plotly=5.24.0
